#############################################################################
# Makefile for building: bin/Games
# Generated by qmake (2.01a) (Qt 4.8.1) on: Thu Apr 13 21:42:28 2017
# Project:  Games.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile Games.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -Ibin
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtSql -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = bin/

####### Files

SOURCES       = main.cpp \
		helper.cpp \
		game2/game2.cpp \
		game1/game1options.cpp \
		game1/game1.cpp \
		game3/game3.cpp \
		gui/mainwidget.cpp \
		gui/gameselection.cpp \
		gui/gamemainmenu.cpp \
		game1/cannon.cpp \
		game1/game1scene.cpp \
		game1/sheep1.cpp \
		game1/barn.cpp \
		game2/game2options.cpp \
		game3/game3options.cpp \
		game2/game2scene.cpp \
		game3/game3scene.cpp \
		game3/dot.cpp \
		game2/tile.cpp \
		game2/sheep2.cpp \
		game3/horizontalline.cpp \
		game3/verticalline.cpp \
		game3/box.cpp \
		game3/line.cpp \
		gameover.cpp \
		account/myaccount.cpp \
		account/qcustomplot.cpp bin/moc_game2.cpp \
		bin/moc_game1options.cpp \
		bin/moc_game1.cpp \
		bin/moc_game3.cpp \
		bin/moc_mainwidget.cpp \
		bin/moc_gameselection.cpp \
		bin/moc_gamemainmenu.cpp \
		bin/moc_cannon.cpp \
		bin/moc_game1scene.cpp \
		bin/moc_sheep1.cpp \
		bin/moc_barn.cpp \
		bin/moc_game2options.cpp \
		bin/moc_game3options.cpp \
		bin/moc_game2scene.cpp \
		bin/moc_game3scene.cpp \
		bin/moc_dot.cpp \
		bin/moc_tile.cpp \
		bin/moc_sheep2.cpp \
		bin/moc_horizontalline.cpp \
		bin/moc_verticalline.cpp \
		bin/moc_box.cpp \
		bin/moc_line.cpp \
		bin/moc_gameover.cpp \
		bin/moc_myaccount.cpp \
		bin/moc_qcustomplot.cpp
OBJECTS       = bin/main.o \
		bin/helper.o \
		bin/game2.o \
		bin/game1options.o \
		bin/game1.o \
		bin/game3.o \
		bin/mainwidget.o \
		bin/gameselection.o \
		bin/gamemainmenu.o \
		bin/cannon.o \
		bin/game1scene.o \
		bin/sheep1.o \
		bin/barn.o \
		bin/game2options.o \
		bin/game3options.o \
		bin/game2scene.o \
		bin/game3scene.o \
		bin/dot.o \
		bin/tile.o \
		bin/sheep2.o \
		bin/horizontalline.o \
		bin/verticalline.o \
		bin/box.o \
		bin/line.o \
		bin/gameover.o \
		bin/myaccount.o \
		bin/qcustomplot.o \
		bin/moc_game2.o \
		bin/moc_game1options.o \
		bin/moc_game1.o \
		bin/moc_game3.o \
		bin/moc_mainwidget.o \
		bin/moc_gameselection.o \
		bin/moc_gamemainmenu.o \
		bin/moc_cannon.o \
		bin/moc_game1scene.o \
		bin/moc_sheep1.o \
		bin/moc_barn.o \
		bin/moc_game2options.o \
		bin/moc_game3options.o \
		bin/moc_game2scene.o \
		bin/moc_game3scene.o \
		bin/moc_dot.o \
		bin/moc_tile.o \
		bin/moc_sheep2.o \
		bin/moc_horizontalline.o \
		bin/moc_verticalline.o \
		bin/moc_box.o \
		bin/moc_line.o \
		bin/moc_gameover.o \
		bin/moc_myaccount.o \
		bin/moc_qcustomplot.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Games.pro
QMAKE_TARGET  = Games
DESTDIR       = bin/
TARGET        = bin/Games

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Games.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtSql.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile Games.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtSql.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Games.pro

dist: 
	@$(CHK_DIR_EXISTS) bin/Games1.0.0 || $(MKDIR) bin/Games1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) bin/Games1.0.0/ && $(COPY_FILE) --parents helper.h game2/game2.h game1/game1options.h game1/game1.h game3/game3.h gui/mainwidget.h gui/gameselection.h gui/gamemainmenu.h game1/cannon.h game1/game1scene.h game1/sheep1.h game1/barn.h game2/game2options.h game3/game3options.h game2/game2scene.h difficulty.h game3/size.h game3/game3scene.h game3/dot.h game2/tile.h game2/sheep2.h game3/horizontalline.h game3/verticalline.h game3/box.h game3/line.h gameover.h account/myaccount.h account/qcustomplot.h bin/Games1.0.0/ && $(COPY_FILE) --parents main.cpp helper.cpp game2/game2.cpp game1/game1options.cpp game1/game1.cpp game3/game3.cpp gui/mainwidget.cpp gui/gameselection.cpp gui/gamemainmenu.cpp game1/cannon.cpp game1/game1scene.cpp game1/sheep1.cpp game1/barn.cpp game2/game2options.cpp game3/game3options.cpp game2/game2scene.cpp game3/game3scene.cpp game3/dot.cpp game2/tile.cpp game2/sheep2.cpp game3/horizontalline.cpp game3/verticalline.cpp game3/box.cpp game3/line.cpp gameover.cpp account/myaccount.cpp account/qcustomplot.cpp bin/Games1.0.0/ && (cd `dirname bin/Games1.0.0` && $(TAR) Games1.0.0.tar Games1.0.0 && $(COMPRESS) Games1.0.0.tar) && $(MOVE) `dirname bin/Games1.0.0`/Games1.0.0.tar.gz . && $(DEL_FILE) -r bin/Games1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: bin/moc_game2.cpp bin/moc_game1options.cpp bin/moc_game1.cpp bin/moc_game3.cpp bin/moc_mainwidget.cpp bin/moc_gameselection.cpp bin/moc_gamemainmenu.cpp bin/moc_cannon.cpp bin/moc_game1scene.cpp bin/moc_sheep1.cpp bin/moc_barn.cpp bin/moc_game2options.cpp bin/moc_game3options.cpp bin/moc_game2scene.cpp bin/moc_game3scene.cpp bin/moc_dot.cpp bin/moc_tile.cpp bin/moc_sheep2.cpp bin/moc_horizontalline.cpp bin/moc_verticalline.cpp bin/moc_box.cpp bin/moc_line.cpp bin/moc_gameover.cpp bin/moc_myaccount.cpp bin/moc_qcustomplot.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) bin/moc_game2.cpp bin/moc_game1options.cpp bin/moc_game1.cpp bin/moc_game3.cpp bin/moc_mainwidget.cpp bin/moc_gameselection.cpp bin/moc_gamemainmenu.cpp bin/moc_cannon.cpp bin/moc_game1scene.cpp bin/moc_sheep1.cpp bin/moc_barn.cpp bin/moc_game2options.cpp bin/moc_game3options.cpp bin/moc_game2scene.cpp bin/moc_game3scene.cpp bin/moc_dot.cpp bin/moc_tile.cpp bin/moc_sheep2.cpp bin/moc_horizontalline.cpp bin/moc_verticalline.cpp bin/moc_box.cpp bin/moc_line.cpp bin/moc_gameover.cpp bin/moc_myaccount.cpp bin/moc_qcustomplot.cpp
bin/moc_game2.cpp: difficulty.h \
		game2/game2scene.h \
		game2/tile.h \
		game2/sheep2.h \
		gameover.h \
		game2/game2.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) game2/game2.h -o bin/moc_game2.cpp

bin/moc_game1options.cpp: game1/game1options.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) game1/game1options.h -o bin/moc_game1options.cpp

bin/moc_game1.cpp: game1/game1scene.h \
		game1/cannon.h \
		game1/sheep1.h \
		game1/barn.h \
		gameover.h \
		game1/game1.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) game1/game1.h -o bin/moc_game1.cpp

bin/moc_game3.cpp: difficulty.h \
		game3/size.h \
		game3/game3scene.h \
		game3/dot.h \
		game3/horizontalline.h \
		game3/line.h \
		game3/box.h \
		game3/verticalline.h \
		gameover.h \
		game3/game3.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) game3/game3.h -o bin/moc_game3.cpp

bin/moc_mainwidget.cpp: gui/mainwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) gui/mainwidget.h -o bin/moc_mainwidget.cpp

bin/moc_gameselection.cpp: gui/gameselection.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) gui/gameselection.h -o bin/moc_gameselection.cpp

bin/moc_gamemainmenu.cpp: gui/gamemainmenu.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) gui/gamemainmenu.h -o bin/moc_gamemainmenu.cpp

bin/moc_cannon.cpp: game1/cannon.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) game1/cannon.h -o bin/moc_cannon.cpp

bin/moc_game1scene.cpp: game1/cannon.h \
		game1/sheep1.h \
		game1/barn.h \
		gameover.h \
		game1/game1scene.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) game1/game1scene.h -o bin/moc_game1scene.cpp

bin/moc_sheep1.cpp: game1/sheep1.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) game1/sheep1.h -o bin/moc_sheep1.cpp

bin/moc_barn.cpp: game1/barn.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) game1/barn.h -o bin/moc_barn.cpp

bin/moc_game2options.cpp: difficulty.h \
		game2/game2options.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) game2/game2options.h -o bin/moc_game2options.cpp

bin/moc_game3options.cpp: difficulty.h \
		game3/size.h \
		game3/game3options.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) game3/game3options.h -o bin/moc_game3options.cpp

bin/moc_game2scene.cpp: difficulty.h \
		game2/tile.h \
		game2/sheep2.h \
		gameover.h \
		game2/game2scene.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) game2/game2scene.h -o bin/moc_game2scene.cpp

bin/moc_game3scene.cpp: difficulty.h \
		game3/size.h \
		game3/dot.h \
		game3/horizontalline.h \
		game3/line.h \
		game3/box.h \
		game3/verticalline.h \
		gameover.h \
		game3/game3scene.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) game3/game3scene.h -o bin/moc_game3scene.cpp

bin/moc_dot.cpp: game3/dot.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) game3/dot.h -o bin/moc_dot.cpp

bin/moc_tile.cpp: game2/tile.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) game2/tile.h -o bin/moc_tile.cpp

bin/moc_sheep2.cpp: game2/tile.h \
		game2/sheep2.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) game2/sheep2.h -o bin/moc_sheep2.cpp

bin/moc_horizontalline.cpp: game3/line.h \
		game3/box.h \
		game3/horizontalline.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) game3/horizontalline.h -o bin/moc_horizontalline.cpp

bin/moc_verticalline.cpp: game3/line.h \
		game3/box.h \
		game3/verticalline.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) game3/verticalline.h -o bin/moc_verticalline.cpp

bin/moc_box.cpp: game3/box.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) game3/box.h -o bin/moc_box.cpp

bin/moc_line.cpp: game3/line.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) game3/line.h -o bin/moc_line.cpp

bin/moc_gameover.cpp: gameover.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) gameover.h -o bin/moc_gameover.cpp

bin/moc_myaccount.cpp: account/qcustomplot.h \
		account/myaccount.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) account/myaccount.h -o bin/moc_myaccount.cpp

bin/moc_qcustomplot.cpp: account/qcustomplot.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) account/qcustomplot.h -o bin/moc_qcustomplot.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

bin/main.o: main.cpp gui/mainwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/main.o main.cpp

bin/helper.o: helper.cpp helper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/helper.o helper.cpp

bin/game2.o: game2/game2.cpp game2/game2.h \
		difficulty.h \
		game2/game2scene.h \
		game2/tile.h \
		game2/sheep2.h \
		gameover.h \
		helper.h \
		gui/gamemainmenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/game2.o game2/game2.cpp

bin/game1options.o: game1/game1options.cpp game1/game1options.h \
		helper.h \
		gui/gamemainmenu.h \
		game1/game1.h \
		game1/game1scene.h \
		game1/cannon.h \
		game1/sheep1.h \
		game1/barn.h \
		gameover.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/game1options.o game1/game1options.cpp

bin/game1.o: game1/game1.cpp game1/game1.h \
		game1/game1scene.h \
		game1/cannon.h \
		game1/sheep1.h \
		game1/barn.h \
		gameover.h \
		helper.h \
		gui/gamemainmenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/game1.o game1/game1.cpp

bin/game3.o: game3/game3.cpp game3/game3.h \
		difficulty.h \
		game3/size.h \
		game3/game3scene.h \
		game3/dot.h \
		game3/horizontalline.h \
		game3/line.h \
		game3/box.h \
		game3/verticalline.h \
		gameover.h \
		helper.h \
		gui/gamemainmenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/game3.o game3/game3.cpp

bin/mainwidget.o: gui/mainwidget.cpp gui/mainwidget.h \
		gui/gameselection.h \
		helper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/mainwidget.o gui/mainwidget.cpp

bin/gameselection.o: gui/gameselection.cpp gui/gameselection.h \
		helper.h \
		gui/mainwidget.h \
		gui/gamemainmenu.h \
		account/myaccount.h \
		account/qcustomplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/gameselection.o gui/gameselection.cpp

bin/gamemainmenu.o: gui/gamemainmenu.cpp gui/gamemainmenu.h \
		helper.h \
		game1/game1options.h \
		game2/game2options.h \
		difficulty.h \
		game3/game3options.h \
		game3/size.h \
		game1/game1.h \
		game1/game1scene.h \
		game1/cannon.h \
		game1/sheep1.h \
		game1/barn.h \
		gameover.h \
		game2/game2.h \
		game2/game2scene.h \
		game2/tile.h \
		game2/sheep2.h \
		game3/game3.h \
		game3/game3scene.h \
		game3/dot.h \
		game3/horizontalline.h \
		game3/line.h \
		game3/box.h \
		game3/verticalline.h \
		gui/gameselection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/gamemainmenu.o gui/gamemainmenu.cpp

bin/cannon.o: game1/cannon.cpp game1/cannon.h \
		game1/game1scene.h \
		game1/sheep1.h \
		game1/barn.h \
		gameover.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/cannon.o game1/cannon.cpp

bin/game1scene.o: game1/game1scene.cpp game1/game1scene.h \
		game1/cannon.h \
		game1/sheep1.h \
		game1/barn.h \
		gameover.h \
		helper.h \
		game1/game1options.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/game1scene.o game1/game1scene.cpp

bin/sheep1.o: game1/sheep1.cpp game1/sheep1.h \
		helper.h \
		game1/game1scene.h \
		game1/cannon.h \
		game1/barn.h \
		gameover.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/sheep1.o game1/sheep1.cpp

bin/barn.o: game1/barn.cpp game1/barn.h \
		game1/game1scene.h \
		game1/cannon.h \
		game1/sheep1.h \
		gameover.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/barn.o game1/barn.cpp

bin/game2options.o: game2/game2options.cpp game2/game2options.h \
		difficulty.h \
		helper.h \
		game2/game2.h \
		game2/game2scene.h \
		game2/tile.h \
		game2/sheep2.h \
		gameover.h \
		gui/gamemainmenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/game2options.o game2/game2options.cpp

bin/game3options.o: game3/game3options.cpp game3/game3options.h \
		difficulty.h \
		game3/size.h \
		helper.h \
		game3/game3.h \
		game3/game3scene.h \
		game3/dot.h \
		game3/horizontalline.h \
		game3/line.h \
		game3/box.h \
		game3/verticalline.h \
		gameover.h \
		gui/gamemainmenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/game3options.o game3/game3options.cpp

bin/game2scene.o: game2/game2scene.cpp game2/game2scene.h \
		difficulty.h \
		game2/tile.h \
		game2/sheep2.h \
		gameover.h \
		helper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/game2scene.o game2/game2scene.cpp

bin/game3scene.o: game3/game3scene.cpp game3/game3scene.h \
		difficulty.h \
		game3/size.h \
		game3/dot.h \
		game3/horizontalline.h \
		game3/line.h \
		game3/box.h \
		game3/verticalline.h \
		gameover.h \
		helper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/game3scene.o game3/game3scene.cpp

bin/dot.o: game3/dot.cpp game3/dot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/dot.o game3/dot.cpp

bin/tile.o: game2/tile.cpp game2/tile.h \
		game2/game2scene.h \
		difficulty.h \
		game2/sheep2.h \
		gameover.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/tile.o game2/tile.cpp

bin/sheep2.o: game2/sheep2.cpp game2/sheep2.h \
		game2/tile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/sheep2.o game2/sheep2.cpp

bin/horizontalline.o: game3/horizontalline.cpp game3/horizontalline.h \
		game3/line.h \
		game3/box.h \
		game3/game3scene.h \
		difficulty.h \
		game3/size.h \
		game3/dot.h \
		game3/verticalline.h \
		gameover.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/horizontalline.o game3/horizontalline.cpp

bin/verticalline.o: game3/verticalline.cpp game3/verticalline.h \
		game3/line.h \
		game3/box.h \
		game3/game3scene.h \
		difficulty.h \
		game3/size.h \
		game3/dot.h \
		game3/horizontalline.h \
		gameover.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/verticalline.o game3/verticalline.cpp

bin/box.o: game3/box.cpp game3/box.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/box.o game3/box.cpp

bin/line.o: game3/line.cpp game3/line.h \
		game3/game3scene.h \
		difficulty.h \
		game3/size.h \
		game3/dot.h \
		game3/horizontalline.h \
		game3/box.h \
		game3/verticalline.h \
		gameover.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/line.o game3/line.cpp

bin/gameover.o: gameover.cpp gameover.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/gameover.o gameover.cpp

bin/myaccount.o: account/myaccount.cpp account/myaccount.h \
		account/qcustomplot.h \
		helper.h \
		gui/gameselection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/myaccount.o account/myaccount.cpp

bin/qcustomplot.o: account/qcustomplot.cpp account/qcustomplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/qcustomplot.o account/qcustomplot.cpp

bin/moc_game2.o: bin/moc_game2.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_game2.o bin/moc_game2.cpp

bin/moc_game1options.o: bin/moc_game1options.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_game1options.o bin/moc_game1options.cpp

bin/moc_game1.o: bin/moc_game1.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_game1.o bin/moc_game1.cpp

bin/moc_game3.o: bin/moc_game3.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_game3.o bin/moc_game3.cpp

bin/moc_mainwidget.o: bin/moc_mainwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_mainwidget.o bin/moc_mainwidget.cpp

bin/moc_gameselection.o: bin/moc_gameselection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_gameselection.o bin/moc_gameselection.cpp

bin/moc_gamemainmenu.o: bin/moc_gamemainmenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_gamemainmenu.o bin/moc_gamemainmenu.cpp

bin/moc_cannon.o: bin/moc_cannon.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_cannon.o bin/moc_cannon.cpp

bin/moc_game1scene.o: bin/moc_game1scene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_game1scene.o bin/moc_game1scene.cpp

bin/moc_sheep1.o: bin/moc_sheep1.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_sheep1.o bin/moc_sheep1.cpp

bin/moc_barn.o: bin/moc_barn.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_barn.o bin/moc_barn.cpp

bin/moc_game2options.o: bin/moc_game2options.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_game2options.o bin/moc_game2options.cpp

bin/moc_game3options.o: bin/moc_game3options.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_game3options.o bin/moc_game3options.cpp

bin/moc_game2scene.o: bin/moc_game2scene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_game2scene.o bin/moc_game2scene.cpp

bin/moc_game3scene.o: bin/moc_game3scene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_game3scene.o bin/moc_game3scene.cpp

bin/moc_dot.o: bin/moc_dot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_dot.o bin/moc_dot.cpp

bin/moc_tile.o: bin/moc_tile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_tile.o bin/moc_tile.cpp

bin/moc_sheep2.o: bin/moc_sheep2.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_sheep2.o bin/moc_sheep2.cpp

bin/moc_horizontalline.o: bin/moc_horizontalline.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_horizontalline.o bin/moc_horizontalline.cpp

bin/moc_verticalline.o: bin/moc_verticalline.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_verticalline.o bin/moc_verticalline.cpp

bin/moc_box.o: bin/moc_box.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_box.o bin/moc_box.cpp

bin/moc_line.o: bin/moc_line.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_line.o bin/moc_line.cpp

bin/moc_gameover.o: bin/moc_gameover.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_gameover.o bin/moc_gameover.cpp

bin/moc_myaccount.o: bin/moc_myaccount.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_myaccount.o bin/moc_myaccount.cpp

bin/moc_qcustomplot.o: bin/moc_qcustomplot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_qcustomplot.o bin/moc_qcustomplot.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

